### PR TITLE
Aliased apply_patch to applyPatch

### PR DESCRIPTION
**Pull request by alex94puchades**

### CODE REVIEW

**Comment by alex94puchades** [comment]
Addresses #19

**Comment by almost** [comment]
Thanks for your Pull Request. You're correct that camel case is the more usual style and I really should have done it that way. However, I'd rather not change the interface of the library now it's been out for a while, that's just making unnecessary pain for users of the library.

**Comment by alex94puchades** [comment]
Sure, it's no big deal, just cosmetic. I'm curious however, ruby background
perhaps?

--
Álex Puchades

**Comment by almost** [comment]
Python :)

Although usually I know better, this was a few years ago so I'm not sure exactly why I went with `snake_case`

**Pull request closed without merging**
