### PR TITLE
Closes #21

### LINKED ISSUE #21: { op='copy' } is not standard compliant
According to the [rfc](https://tools.ietf.org/html/rfc6902#section-4.5), the following code should give an error:
```js
jsonpatch.apply_patch({}, { op: 'copy', from: '/invalid', path: '/dest' })
```
However, it returns ```{ dest: undefined }```

### PR DESCRIPTION
**Pull request by agraboso**

### CODE REVIEW

**Comment by almost** [comment]
Thanks!

**Comment by almost** [comment]
Sorry, I had to revert this. It fails one of the tests. I didn't have time to properly check so maybe it's the test that's at fault?

**Comment by agraboso** [comment]
My apologies for not checking the tests before submitting this PR.

The failing test asks for `JSONPointer.get()` to return undefined for `/numbers/-`, while the PR makes it throw a `PatchApplyError`.

Section 4 of the [JSONPointer spec](http://tools.ietf.org/html/rfc6901) defines the character `-` as

> the (nonexistent) member after the last array element

Section 7 says

> Error conditions include, but are not limited to:
> -  Invalid pointer syntax
> -  A pointer that references a nonexistent value

> This specification does not define how errors are handled.  An application of JSON Pointer SHOULD specify the impact and handling of each type of error.

So `/numbers/-` does produce an error condition, as defined by the spec. Returning undefined or throwing are probably the only two reasonable ways of handling such an error condition.

If the error condition is to be handled by throwing, the test must be rewritten to separate the `/numbers/-` case. If the error condition is to be handled by returning undefined, this PR should be slightly changed --- essentially moving the error-checking condition to the `compileOperation` function. Let me know which of the two you want to go with and I can pull together a quick PR.

**Comment by agraboso** [comment]
See #25. My reasoning for sticking to the choice of throwing when trying to `get()` a non-existent path instead of returning `undefined` is that, if we were to do the latter, we would run into the problem of existing paths with value `undefined` (though I'm not even sure that's valid JSON) getting rejected.

**Comment by almost** [comment]
I agree with your reasoning, thanks!

**Pull request merged**
